# Generated by Django 5.0.3 on 2024-04-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Sorry, this email is already in use.'}, max_length=255, unique=True, verbose_name='email'),
        ),
    ]
