# Generated by Django 5.0.3 on 2024-03-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_remove_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.image')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='images',
            field=models.ManyToManyField(through='product_catalog.ImageAssociation', to='product_catalog.image'),
        ),
    ]
