# Generated by Django 5.0.3 on 2024-03-25 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0004_image_imageassociation_country_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(through='product_catalog.ImageAssociation', to='product_catalog.image'),
        ),
        migrations.AlterField(
            model_name='imageassociation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product'),
        ),
    ]
