# Generated by Django 5.0.3 on 2024-03-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0005_remove_country_images_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageassociation',
            old_name='model',
            new_name='product',
        ),
    ]
